// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto_C2GS.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HHFramework.Proto {

  /// <summary>Holder for reflection information generated from Proto_C2GS.proto</summary>
  public static partial class ProtoC2GSReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto_C2GS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoC2GSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQcm90b19DMkdTLnByb3RvEhFISEZyYW1ld29yay5Qcm90bxoSUHJvdG9f",
            "Q29tbW9uLnByb3RvIqsBCg5DMkdTX0NsaWNrTW92ZRIrCgdDdXJyUG9zGAEg",
            "ASgLMhouSEhGcmFtZXdvcmsuUHJvdG8uVmVjdG9yMxItCglUYXJnZXRQb3MY",
            "AiABKAsyGi5ISEZyYW1ld29yay5Qcm90by5WZWN0b3IzEhYKDlRhcmdldFJv",
            "bGVUeXBlGAMgASgFEhQKDFRhcmdldFJvbGVJZBgEIAEoAxIPCgdTa2lsbElk",
            "GAUgASgFIm0KEUMyR1NfSm95c3RpY2tNb3ZlEisKB0N1cnJQb3MYASABKAsy",
            "Gi5ISEZyYW1ld29yay5Qcm90by5WZWN0b3IzEisKB01vdmVEaXIYAiABKAsy",
            "Gi5ISEZyYW1ld29yay5Qcm90by5WZWN0b3IzIlMKEUMyR1NfSm95c3RpY2tT",
            "dG9wEisKB0N1cnJQb3MYASABKAsyGi5ISEZyYW1ld29yay5Qcm90by5WZWN0",
            "b3IzEhEKCVJvdGF0aW9uWRgCIAEoAiIkChJDMkdTX0VudGVyX0FPSUFyZWES",
            "DgoGQXJlYUlkGAEgASgFIm8KEUMyR1NfUm9sZVRyYW5zZmVyEisKB0N1cnJQ",
            "b3MYASABKAsyGi5ISEZyYW1ld29yay5Qcm90by5WZWN0b3IzEi0KCVRhcmdl",
            "dFBvcxgCIAEoCzIaLkhIRnJhbWV3b3JrLlByb3RvLlZlY3RvcjMiTwoOQzJH",
            "U19QbGF5U2tpbGwSFgoOVGFyZ2V0Um9sZVR5cGUYASABKAUSFAoMVGFyZ2V0",
            "Um9sZUlkGAIgASgDEg8KB1NraWxsSWQYAyABKAUiJwoTQzJHU19FbnRlcl9S",
            "ZWdpb25JZBIQCghSZWdpb25JZBgBIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HHFramework.Proto.ProtoCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_ClickMove), global::HHFramework.Proto.C2GS_ClickMove.Parser, new[]{ "CurrPos", "TargetPos", "TargetRoleType", "TargetRoleId", "SkillId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_JoystickMove), global::HHFramework.Proto.C2GS_JoystickMove.Parser, new[]{ "CurrPos", "MoveDir" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_JoystickStop), global::HHFramework.Proto.C2GS_JoystickStop.Parser, new[]{ "CurrPos", "RotationY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_Enter_AOIArea), global::HHFramework.Proto.C2GS_Enter_AOIArea.Parser, new[]{ "AreaId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_RoleTransfer), global::HHFramework.Proto.C2GS_RoleTransfer.Parser, new[]{ "CurrPos", "TargetPos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_PlaySkill), global::HHFramework.Proto.C2GS_PlaySkill.Parser, new[]{ "TargetRoleType", "TargetRoleId", "SkillId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.C2GS_Enter_RegionId), global::HHFramework.Proto.C2GS_Enter_RegionId.Parser, new[]{ "RegionId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///玩家向服务器发送点击移动消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_ClickMove : HHFramework.IProto, pb::IMessage<C2GS_ClickMove>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_ClickMove;
    public string ProtoEnName => "C2GS_ClickMove";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_ClickMove> _parser = new pb::MessageParser<C2GS_ClickMove>(() => new C2GS_ClickMove());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_ClickMove> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_ClickMove() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_ClickMove(C2GS_ClickMove other) : this() {
      currPos_ = other.currPos_ != null ? other.currPos_.Clone() : null;
      targetPos_ = other.targetPos_ != null ? other.targetPos_.Clone() : null;
      targetRoleType_ = other.targetRoleType_;
      targetRoleId_ = other.targetRoleId_;
      skillId_ = other.skillId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_ClickMove Clone() {
      return new C2GS_ClickMove(this);
    }

    /// <summary>Field number for the "CurrPos" field.</summary>
    public const int CurrPosFieldNumber = 1;
    private global::HHFramework.Proto.Vector3 currPos_;
    /// <summary>
    ///当前位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 CurrPos {
      get { return currPos_; }
      set {
        currPos_ = value;
      }
    }

    /// <summary>Field number for the "TargetPos" field.</summary>
    public const int TargetPosFieldNumber = 2;
    private global::HHFramework.Proto.Vector3 targetPos_;
    /// <summary>
    ///目标点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 TargetPos {
      get { return targetPos_; }
      set {
        targetPos_ = value;
      }
    }

    /// <summary>Field number for the "TargetRoleType" field.</summary>
    public const int TargetRoleTypeFieldNumber = 3;
    private int targetRoleType_;
    /// <summary>
    ///锁定目标角色类型:0自己/1其他玩家/2怪
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetRoleType {
      get { return targetRoleType_; }
      set {
        targetRoleType_ = value;
      }
    }

    /// <summary>Field number for the "TargetRoleId" field.</summary>
    public const int TargetRoleIdFieldNumber = 4;
    private long targetRoleId_;
    /// <summary>
    ///锁定目标角色编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetRoleId {
      get { return targetRoleId_; }
      set {
        targetRoleId_ = value;
      }
    }

    /// <summary>Field number for the "SkillId" field.</summary>
    public const int SkillIdFieldNumber = 5;
    private int skillId_;
    /// <summary>
    ///移动后发动技能的编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_ClickMove);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_ClickMove other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrPos, other.CurrPos)) return false;
      if (!object.Equals(TargetPos, other.TargetPos)) return false;
      if (TargetRoleType != other.TargetRoleType) return false;
      if (TargetRoleId != other.TargetRoleId) return false;
      if (SkillId != other.SkillId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currPos_ != null) hash ^= CurrPos.GetHashCode();
      if (targetPos_ != null) hash ^= TargetPos.GetHashCode();
      if (TargetRoleType != 0) hash ^= TargetRoleType.GetHashCode();
      if (TargetRoleId != 0L) hash ^= TargetRoleId.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (targetPos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPos);
      }
      if (TargetRoleType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TargetRoleId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (targetPos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPos);
      }
      if (TargetRoleType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TargetRoleId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrPos);
      }
      if (targetPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPos);
      }
      if (TargetRoleType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetRoleId);
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_ClickMove other) {
      if (other == null) {
        return;
      }
      if (other.currPos_ != null) {
        if (currPos_ == null) {
          CurrPos = new global::HHFramework.Proto.Vector3();
        }
        CurrPos.MergeFrom(other.CurrPos);
      }
      if (other.targetPos_ != null) {
        if (targetPos_ == null) {
          TargetPos = new global::HHFramework.Proto.Vector3();
        }
        TargetPos.MergeFrom(other.TargetPos);
      }
      if (other.TargetRoleType != 0) {
        TargetRoleType = other.TargetRoleType;
      }
      if (other.TargetRoleId != 0L) {
        TargetRoleId = other.TargetRoleId;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (targetPos_ == null) {
              TargetPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(TargetPos);
            break;
          }
          case 24: {
            TargetRoleType = input.ReadInt32();
            break;
          }
          case 32: {
            TargetRoleId = input.ReadInt64();
            break;
          }
          case 40: {
            SkillId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (targetPos_ == null) {
              TargetPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(TargetPos);
            break;
          }
          case 24: {
            TargetRoleType = input.ReadInt32();
            break;
          }
          case 32: {
            TargetRoleId = input.ReadInt64();
            break;
          }
          case 40: {
            SkillId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送摇杆移动消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_JoystickMove : HHFramework.IProto, pb::IMessage<C2GS_JoystickMove>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_JoystickMove;
    public string ProtoEnName => "C2GS_JoystickMove";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_JoystickMove> _parser = new pb::MessageParser<C2GS_JoystickMove>(() => new C2GS_JoystickMove());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_JoystickMove> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickMove() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickMove(C2GS_JoystickMove other) : this() {
      currPos_ = other.currPos_ != null ? other.currPos_.Clone() : null;
      moveDir_ = other.moveDir_ != null ? other.moveDir_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickMove Clone() {
      return new C2GS_JoystickMove(this);
    }

    /// <summary>Field number for the "CurrPos" field.</summary>
    public const int CurrPosFieldNumber = 1;
    private global::HHFramework.Proto.Vector3 currPos_;
    /// <summary>
    ///当前位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 CurrPos {
      get { return currPos_; }
      set {
        currPos_ = value;
      }
    }

    /// <summary>Field number for the "MoveDir" field.</summary>
    public const int MoveDirFieldNumber = 2;
    private global::HHFramework.Proto.Vector3 moveDir_;
    /// <summary>
    ///移动方向
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 MoveDir {
      get { return moveDir_; }
      set {
        moveDir_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_JoystickMove);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_JoystickMove other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrPos, other.CurrPos)) return false;
      if (!object.Equals(MoveDir, other.MoveDir)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currPos_ != null) hash ^= CurrPos.GetHashCode();
      if (moveDir_ != null) hash ^= MoveDir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (moveDir_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MoveDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (moveDir_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MoveDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrPos);
      }
      if (moveDir_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MoveDir);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_JoystickMove other) {
      if (other == null) {
        return;
      }
      if (other.currPos_ != null) {
        if (currPos_ == null) {
          CurrPos = new global::HHFramework.Proto.Vector3();
        }
        CurrPos.MergeFrom(other.CurrPos);
      }
      if (other.moveDir_ != null) {
        if (moveDir_ == null) {
          MoveDir = new global::HHFramework.Proto.Vector3();
        }
        MoveDir.MergeFrom(other.MoveDir);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (moveDir_ == null) {
              MoveDir = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(MoveDir);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (moveDir_ == null) {
              MoveDir = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(MoveDir);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送抬起摇杆消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_JoystickStop : HHFramework.IProto, pb::IMessage<C2GS_JoystickStop>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_JoystickStop;
    public string ProtoEnName => "C2GS_JoystickStop";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_JoystickStop> _parser = new pb::MessageParser<C2GS_JoystickStop>(() => new C2GS_JoystickStop());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_JoystickStop> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickStop() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickStop(C2GS_JoystickStop other) : this() {
      currPos_ = other.currPos_ != null ? other.currPos_.Clone() : null;
      rotationY_ = other.rotationY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_JoystickStop Clone() {
      return new C2GS_JoystickStop(this);
    }

    /// <summary>Field number for the "CurrPos" field.</summary>
    public const int CurrPosFieldNumber = 1;
    private global::HHFramework.Proto.Vector3 currPos_;
    /// <summary>
    ///当前位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 CurrPos {
      get { return currPos_; }
      set {
        currPos_ = value;
      }
    }

    /// <summary>Field number for the "RotationY" field.</summary>
    public const int RotationYFieldNumber = 2;
    private float rotationY_;
    /// <summary>
    ///旋转
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotationY {
      get { return rotationY_; }
      set {
        rotationY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_JoystickStop);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_JoystickStop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrPos, other.CurrPos)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotationY, other.RotationY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currPos_ != null) hash ^= CurrPos.GetHashCode();
      if (RotationY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotationY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (RotationY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(RotationY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (RotationY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(RotationY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrPos);
      }
      if (RotationY != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_JoystickStop other) {
      if (other == null) {
        return;
      }
      if (other.currPos_ != null) {
        if (currPos_ == null) {
          CurrPos = new global::HHFramework.Proto.Vector3();
        }
        CurrPos.MergeFrom(other.CurrPos);
      }
      if (other.RotationY != 0F) {
        RotationY = other.RotationY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 21: {
            RotationY = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 21: {
            RotationY = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送进入AOI区域消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_Enter_AOIArea : HHFramework.IProto, pb::IMessage<C2GS_Enter_AOIArea>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_Enter_AOIArea;
    public string ProtoEnName => "C2GS_Enter_AOIArea";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_Enter_AOIArea> _parser = new pb::MessageParser<C2GS_Enter_AOIArea>(() => new C2GS_Enter_AOIArea());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_Enter_AOIArea> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_AOIArea() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_AOIArea(C2GS_Enter_AOIArea other) : this() {
      areaId_ = other.areaId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_AOIArea Clone() {
      return new C2GS_Enter_AOIArea(this);
    }

    /// <summary>Field number for the "AreaId" field.</summary>
    public const int AreaIdFieldNumber = 1;
    private int areaId_;
    /// <summary>
    ///场景编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AreaId {
      get { return areaId_; }
      set {
        areaId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_Enter_AOIArea);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_Enter_AOIArea other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AreaId != other.AreaId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AreaId != 0) hash ^= AreaId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AreaId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AreaId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AreaId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AreaId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AreaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AreaId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_Enter_AOIArea other) {
      if (other == null) {
        return;
      }
      if (other.AreaId != 0) {
        AreaId = other.AreaId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AreaId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AreaId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送传送消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_RoleTransfer : HHFramework.IProto, pb::IMessage<C2GS_RoleTransfer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_RoleTransfer;
    public string ProtoEnName => "C2GS_RoleTransfer";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_RoleTransfer> _parser = new pb::MessageParser<C2GS_RoleTransfer>(() => new C2GS_RoleTransfer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_RoleTransfer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_RoleTransfer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_RoleTransfer(C2GS_RoleTransfer other) : this() {
      currPos_ = other.currPos_ != null ? other.currPos_.Clone() : null;
      targetPos_ = other.targetPos_ != null ? other.targetPos_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_RoleTransfer Clone() {
      return new C2GS_RoleTransfer(this);
    }

    /// <summary>Field number for the "CurrPos" field.</summary>
    public const int CurrPosFieldNumber = 1;
    private global::HHFramework.Proto.Vector3 currPos_;
    /// <summary>
    ///当前位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 CurrPos {
      get { return currPos_; }
      set {
        currPos_ = value;
      }
    }

    /// <summary>Field number for the "TargetPos" field.</summary>
    public const int TargetPosFieldNumber = 2;
    private global::HHFramework.Proto.Vector3 targetPos_;
    /// <summary>
    ///目标点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HHFramework.Proto.Vector3 TargetPos {
      get { return targetPos_; }
      set {
        targetPos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_RoleTransfer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_RoleTransfer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrPos, other.CurrPos)) return false;
      if (!object.Equals(TargetPos, other.TargetPos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currPos_ != null) hash ^= CurrPos.GetHashCode();
      if (targetPos_ != null) hash ^= TargetPos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (targetPos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrPos);
      }
      if (targetPos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrPos);
      }
      if (targetPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_RoleTransfer other) {
      if (other == null) {
        return;
      }
      if (other.currPos_ != null) {
        if (currPos_ == null) {
          CurrPos = new global::HHFramework.Proto.Vector3();
        }
        CurrPos.MergeFrom(other.CurrPos);
      }
      if (other.targetPos_ != null) {
        if (targetPos_ == null) {
          TargetPos = new global::HHFramework.Proto.Vector3();
        }
        TargetPos.MergeFrom(other.TargetPos);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (targetPos_ == null) {
              TargetPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(TargetPos);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currPos_ == null) {
              CurrPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(CurrPos);
            break;
          }
          case 18: {
            if (targetPos_ == null) {
              TargetPos = new global::HHFramework.Proto.Vector3();
            }
            input.ReadMessage(TargetPos);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送播放技能消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_PlaySkill : HHFramework.IProto, pb::IMessage<C2GS_PlaySkill>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_PlaySkill;
    public string ProtoEnName => "C2GS_PlaySkill";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_PlaySkill> _parser = new pb::MessageParser<C2GS_PlaySkill>(() => new C2GS_PlaySkill());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_PlaySkill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_PlaySkill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_PlaySkill(C2GS_PlaySkill other) : this() {
      targetRoleType_ = other.targetRoleType_;
      targetRoleId_ = other.targetRoleId_;
      skillId_ = other.skillId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_PlaySkill Clone() {
      return new C2GS_PlaySkill(this);
    }

    /// <summary>Field number for the "TargetRoleType" field.</summary>
    public const int TargetRoleTypeFieldNumber = 1;
    private int targetRoleType_;
    /// <summary>
    ///锁定目标角色类型:0自己/1其他玩家/2怪
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetRoleType {
      get { return targetRoleType_; }
      set {
        targetRoleType_ = value;
      }
    }

    /// <summary>Field number for the "TargetRoleId" field.</summary>
    public const int TargetRoleIdFieldNumber = 2;
    private long targetRoleId_;
    /// <summary>
    ///锁定目标角色编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetRoleId {
      get { return targetRoleId_; }
      set {
        targetRoleId_ = value;
      }
    }

    /// <summary>Field number for the "SkillId" field.</summary>
    public const int SkillIdFieldNumber = 3;
    private int skillId_;
    /// <summary>
    ///技能编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_PlaySkill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_PlaySkill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetRoleType != other.TargetRoleType) return false;
      if (TargetRoleId != other.TargetRoleId) return false;
      if (SkillId != other.SkillId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetRoleType != 0) hash ^= TargetRoleType.GetHashCode();
      if (TargetRoleId != 0L) hash ^= TargetRoleId.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TargetRoleType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TargetRoleId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TargetRoleType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TargetRoleId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TargetRoleType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetRoleType);
      }
      if (TargetRoleId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetRoleId);
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_PlaySkill other) {
      if (other == null) {
        return;
      }
      if (other.TargetRoleType != 0) {
        TargetRoleType = other.TargetRoleType;
      }
      if (other.TargetRoleId != 0L) {
        TargetRoleId = other.TargetRoleId;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TargetRoleType = input.ReadInt32();
            break;
          }
          case 16: {
            TargetRoleId = input.ReadInt64();
            break;
          }
          case 24: {
            SkillId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TargetRoleType = input.ReadInt32();
            break;
          }
          case 16: {
            TargetRoleId = input.ReadInt64();
            break;
          }
          case 24: {
            SkillId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家向服务器发送到达区域消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class C2GS_Enter_RegionId : HHFramework.IProto, pb::IMessage<C2GS_Enter_RegionId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    public ushort ProtoId => ProtoIdDefine.Proto_C2GS_Enter_RegionId;
    public string ProtoEnName => "C2GS_Enter_RegionId";
    public ProtoCategory Category => ProtoCategory.Client2GameServer;
    private static readonly pb::MessageParser<C2GS_Enter_RegionId> _parser = new pb::MessageParser<C2GS_Enter_RegionId>(() => new C2GS_Enter_RegionId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2GS_Enter_RegionId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoC2GSReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_RegionId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_RegionId(C2GS_Enter_RegionId other) : this() {
      regionId_ = other.regionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2GS_Enter_RegionId Clone() {
      return new C2GS_Enter_RegionId(this);
    }

    /// <summary>Field number for the "RegionId" field.</summary>
    public const int RegionIdFieldNumber = 1;
    private int regionId_;
    /// <summary>
    ///区域编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RegionId {
      get { return regionId_; }
      set {
        regionId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2GS_Enter_RegionId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2GS_Enter_RegionId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RegionId != other.RegionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RegionId != 0) hash ^= RegionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RegionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RegionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RegionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RegionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RegionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RegionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2GS_Enter_RegionId other) {
      if (other == null) {
        return;
      }
      if (other.RegionId != 0) {
        RegionId = other.RegionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RegionId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RegionId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
